source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby ">= 3.1.0"

gem "rails", "~> 7.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.0"
gem "rack-cors", "~> 2.0"
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.11"
gem "faraday", "~> 2.7"
gem "bootsnap", ">= 1.4.4", require: false
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails", "~> 6.0"
  gem "faker", "~> 3.0"
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
end

group :test do
  gem "shoulda-matchers", "~> 5.0"
  gem "database_cleaner-active_record", "~> 2.0"
end
